# Generated by Django 6.0.2 on 2026-03-07 04:55

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_id', models.CharField(blank=True, db_index=True, help_text='Human-readable unique identifier, e.g. FINE-DG-ABCD-00001.', max_length=30, unique=True)),
                ('fine_type', models.CharField(choices=[('overdue', 'Overdue'), ('lost', 'Lost Book'), ('damage', 'Damage'), ('other', 'Other')], default='overdue', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='unpaid', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online / UPI'), ('waiver', 'Waived')], max_length=10)),
                ('payment_ref', models.CharField(blank=True, help_text='Receipt number or gateway reference.', max_length=100)),
                ('transaction_id_snapshot', models.CharField(blank=True, max_length=50)),
                ('member_name', models.CharField(blank=True, max_length=200)),
                ('member_id_snapshot', models.CharField(blank=True, max_length=50)),
                ('book_title', models.CharField(blank=True, max_length=300)),
                ('issue_date_snapshot', models.DateField(blank=True, null=True)),
                ('due_date_snapshot', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='accounts.library')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=60)),
                ('collected_by', models.CharField(blank=True, max_length=150)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=200)),
                ('transaction_id_snapshot', models.CharField(blank=True, max_length=50)),
                ('member_name', models.CharField(blank=True, max_length=200)),
                ('member_id_snapshot', models.CharField(blank=True, max_length=50)),
                ('book_title', models.CharField(blank=True, max_length=300)),
                ('fine_id_snapshot', models.CharField(blank=True, max_length=30)),
                ('fine_type_snapshot', models.CharField(blank=True, max_length=20)),
                ('fine_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('library_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.fine')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.library')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('key_id', models.CharField(blank=True, max_length=100)),
                ('_key_secret_enc', models.CharField(blank=True, db_column='key_secret_enc', help_text='Fernet-encrypted Razorpay key secret.', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='accounts.library')),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, choices=[('stationery', 'Stationery'), ('maintenance', 'Maintenance'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('books', 'Books & Periodicals'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.library')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['library', 'date'], name='finance_exp_library_33093c_idx'), models.Index(fields=['library', 'category'], name='finance_exp_library_df7268_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['library', 'status'], name='finance_fin_library_7a6428_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['library', 'fine_type'], name='finance_fin_library_9c016d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['library', 'status'], name='finance_pay_library_d93af0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['library', 'transaction_date'], name='finance_pay_library_826908_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='finance_pay_receipt_578993_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_payment_id'], name='finance_pay_gateway_741f4e_idx'),
        ),
    ]
