# Generated by Django 6.0.2 on 2026-03-07 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Bengali', 'Bengali'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Nepali', 'Nepali')], max_length=20)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('shelf_location', models.CharField(blank=True, max_length=50)),
                ('total_copies', models.PositiveIntegerField(default=0, help_text='[Deprecated] Use BookCopy records instead. Kept for migration compatibility.')),
                ('available_copies', models.PositiveIntegerField(default=0, help_text='[Deprecated] Use BookCopy records instead. Kept for migration compatibility.')),
                ('cover_image', models.BinaryField(blank=True, null=True)),
                ('cover_mime_type', models.CharField(blank=True, default='image/jpeg', help_text='MIME type of the stored cover image.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'isbn')},
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_id', models.CharField(db_index=True, help_text='Unique physical-copy identifier. Format: DG<LIB3>BK<MM><YY><SERIAL> (14 chars). Example: DGDGRBK0326001. Auto-generated; do not edit manually.', max_length=14, unique=True, verbose_name='Copy ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('lost', 'Lost'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=10)),
                ('borrowed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('copy_number', models.PositiveIntegerField(blank=True, help_text='Sequential copy number within the parent book (1, 2, 3 …).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Book Copy',
                'verbose_name_plural': 'Book Copies',
                'ordering': ['copy_id'],
                'indexes': [models.Index(fields=['book', 'status'], name='books_bookc_book_id_b9abc0_idx')],
            },
        ),
    ]
