# Generated by Django 6.0.2 on 2026-03-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase / replacement price of the book (₹).', max_digits=10, null=True),
        ),
    ]
