# Generated by Django 6.0.2 on 2026-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
