# Generated by Django 6.0.2 on 2026-03-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersettings',
            name='member_id_format',
        ),
    ]
