# Generated by Django 6.0.2 on 2026-03-20 13:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_membersettings_member_id_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Must match accounts.Subscription plan value (basic|silver|gold|pro|enterprise)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('max_books', models.PositiveIntegerField(blank=True, help_text='Max BookCopy records. Blank = unlimited', null=True)),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Max Member records. Blank = unlimited', null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, help_text='Storage cap in GB. Blank = unlimited', null=True)),
                ('features_text', models.TextField(blank=True, help_text='One feature per line')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=80)),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superuser_activity_logs', to='accounts.subscription')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superuser_activity_logs', to='accounts.library')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superuser_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=50)),
                ('library_name', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('void', 'Void')], default='unpaid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='accounts.subscription')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='accounts.library')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=50)),
                ('library_name', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('initial', 'Initial'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('refund', 'Refund'), ('manual', 'Manual')], default='renewal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('gateway', models.CharField(default='Razorpay', help_text='e.g. Razorpay, Stripe, Manual', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='accounts.subscription')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to='accounts.library')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='superuser.invoice')),
            ],
            options={
                'verbose_name': 'Billing Transaction',
                'verbose_name_plural': 'Billing Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['library', 'status'], name='superuser_b_library_2200e1_idx'), models.Index(fields=['library', 'created_at'], name='superuser_b_library_6fa1e1_idx')],
            },
        ),
    ]
