# Generated by Django 6.0.2 on 2026-03-20 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('department', models.CharField(choices=[('executive', 'Executive'), ('tech', 'Technology'), ('sales', 'Sales & Marketing'), ('support', 'Support'), ('operations', 'Operations'), ('qa', 'Quality Assurance'), ('design', 'Design'), ('finance', 'Finance')], default='tech', max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=10, help_text='Hierarchy level: 0=CEO, 1=CTO/VP, 2=Head, 3=Senior, 4=Junior')),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Dict of permission flags e.g. {"can_add_staff": true}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar_color', models.CharField(default='#3d6bff', help_text='Hex color for avatar placeholder', max_length=7)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Private notes visible only to superuser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Who created this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_staff', to='superuser.staffmember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_staff', to='superuser.staffrole')),
                ('secondary_roles', models.ManyToManyField(blank=True, related_name='secondary_staff', to='superuser.staffrole')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['primary_role__level', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dev', 'Development'), ('sales', 'Sales'), ('support', 'Support'), ('qa', 'QA / Testing'), ('design', 'Design'), ('ops', 'Operations'), ('admin', 'Admin'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='superuser.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Task',
                'verbose_name_plural': 'Staff Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='superuser_s_assigne_6b1a94_idx'), models.Index(fields=['assigned_to', 'due_date'], name='superuser_s_assigne_1af1e5_idx')],
            },
        ),
    ]
