# Generated by Django 6.0.2 on 2026-03-07 04:55

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Auto-generated: DG<LIB3>TR<MM><YY><SERIAL>  e.g. DGDOOTR032600003', max_length=30, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('lost_date', models.DateField(blank=True, null=True)),
                ('loan_duration_days', models.PositiveIntegerField(default=14)),
                ('fine_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Copied from LibraryRuleSettings.late_fine at issue time.', max_digits=8)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], db_index=True, default='issued', max_length=20)),
                ('return_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], max_length=20)),
                ('issued_by', models.CharField(blank=True, max_length=150)),
                ('returned_to', models.CharField(blank=True, max_length=150)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fine_paid', models.BooleanField(default=False)),
                ('fine_paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='books.book')),
                ('book_copy', models.ForeignKey(blank=True, help_text='The specific copy that was issued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='books.bookcopy')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_transactions', to='members.member')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('lost', 'Lost'), ('recovered', 'Recovered')], default='missing', max_length=20)),
                ('reported_date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(blank=True, choices=[('lost', 'Book Lost'), ('damaged', 'Severely Damaged'), ('missing', 'Missing - Not Returned'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_paid', models.BooleanField(default=False)),
                ('penalty_reason', models.CharField(blank=True, choices=[('lost', 'Book Lost'), ('damaged', 'Severely Damaged'), ('missing', 'Missing - Not Returned'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missing_book_records', to='books.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.library')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='missing_record', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Missing Book',
                'verbose_name_plural': 'Missing Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['library', 'status'], name='transaction_library_dbbd99_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['library', 'due_date'], name='transaction_library_c5e174_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['library', 'member'], name='transaction_library_850c32_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['book'], name='transaction_book_id_0fb9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='missingbook',
            index=models.Index(fields=['library', 'status'], name='transaction_library_08069a_idx'),
        ),
    ]
