# Generated by Django 6.0.2 on 2026-03-19 08:06

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_membersettings_member_id_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='basic', max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='One-line plan pitch shown on the Plans page.', max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Subscription validity in days (30 = monthly, 365 = yearly).')),
                ('is_free', models.BooleanField(default=False, help_text='If True, payment is bypassed and the plan activates immediately.')),
                ('max_members', models.PositiveIntegerField(default=50, help_text='Max member registrations allowed.')),
                ('max_books', models.PositiveIntegerField(default=500, help_text='Max bibliographic Book records allowed.')),
                ('max_staff', models.PositiveIntegerField(default=2, help_text='Max staff (non-superuser) accounts allowed.')),
                ('max_book_copies', models.PositiveIntegerField(default=1000, help_text='Max total BookCopy records allowed.')),
                ('allow_reports', models.BooleanField(default=True)),
                ('allow_export', models.BooleanField(default=False)),
                ('allow_sms', models.BooleanField(default=False)),
                ('allow_email_reminders', models.BooleanField(default=True)),
                ('allow_api_access', models.BooleanField(default=False)),
                ('allow_custom_branding', models.BooleanField(default=False)),
                ('allow_advance_booking', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False, help_text="Highlight this plan as 'Most Popular'.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from the Plans page.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('pending', 'Pending Payment')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_detail', to='accounts.library')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('manual', 'Manual / Offline')], default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_initiated', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='accounts.library')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='subscriptions.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
