# Generated by Django 6.0.2 on 2026-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateField(blank=True, help_text='Date the trial period ends.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='True once a trial has been started; never resets.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free plan — no payment required; used as post-expiry fallback.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], db_index=True, default='active', max_length=20),
        ),
    ]
