# Generated by Django 6.0.2 on 2026-03-07 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display label, e.g. "1st Year", "Final Year".', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order — lower value appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['order', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full course name.', max_length=200)),
                ('code', models.CharField(help_text='Short course code (e.g. BTECH, MBA).', max_length=20)),
                ('duration', models.PositiveSmallIntegerField(default=3, help_text='Duration of the course in years.')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full department name.', max_length=200)),
                ('code', models.CharField(help_text='Short department code (e.g. CSE, MBA).', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display label, e.g. "Semester 1", "Spring 2025".', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order — lower value appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['order', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher / Faculty'), ('general', 'General Member')], db_index=True, default='student', help_text='Member role: Student, Teacher/Faculty, or General Member.', max_length=20)),
                ('member_id', models.CharField(blank=True, help_text='Unique member ID per owner. Auto-generated if left blank.', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Must be unique per owner.', max_length=254)),
                ('phone', models.CharField(help_text='10-digit mobile number.', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Optional alternate 10-digit number.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('guardian_phone', models.CharField(blank=True, help_text='Parent/guardian 10-digit number.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('photo_mime_type', models.CharField(blank=True, default='image/jpeg', help_text='MIME type of the stored photo (e.g. image/jpeg, image/png).', max_length=50)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_year', models.PositiveSmallIntegerField(blank=True, help_text='Year of admission (e.g. 2022).', null=True)),
                ('specialization', models.CharField(blank=True, help_text='Specialization or elective subject (optional).', max_length=200, null=True)),
                ('academic_notes', models.TextField(blank=True, help_text='Additional academic remarks or notes.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('passout', 'Pass Out')], default='active', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the member record was created.')),
                ('inactive_since', models.DateTimeField(blank=True, help_text="Automatically set when status changes to 'inactive'.", null=True)),
                ('inactive_reason', models.TextField(blank=True, help_text='Reason for marking the member inactive.', null=True)),
                ('clearance_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared')], default='pending', help_text='Library clearance status (all books returned, dues cleared).', max_length=20)),
                ('clearance_date', models.DateTimeField(blank=True, help_text='Timestamp when clearance was granted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, help_text='Staff member who granted clearance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_members', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.department')),
                ('owner', models.ForeignKey(help_text='Library admin who owns this member record.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, help_text='Academic year (e.g. "1st Year", "Final Year").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.academicyear')),
                ('semester', models.ForeignKey(blank=True, help_text='Current semester (e.g. "Semester 3").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.semester')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'email'), ('owner', 'member_id')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500)),
                ('book_author', models.CharField(blank=True, max_length=500, null=True)),
                ('book_isbn', models.CharField(blank=True, help_text='ISBN-10 or ISBN-13.', max_length=50, null=True)),
                ('book_accession_number', models.CharField(blank=True, help_text='Library accession / barcode number of the physical copy.', max_length=50, null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the book was issued.')),
                ('due_date', models.DateField(help_text='Date by which the book must be returned.')),
                ('return_date', models.DateTimeField(blank=True, help_text="Actual return timestamp. Auto-set on save when status = 'returned'.", null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='issued', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fine amount in local currency.', max_digits=10)),
                ('fine_paid', models.BooleanField(default=False, help_text='True once the fine has been collected.')),
                ('fine_paid_date', models.DateTimeField(blank=True, help_text='Timestamp when the fine was paid.', null=True)),
                ('issue_notes', models.TextField(blank=True, help_text='Condition of the book at the time of issue, etc.', null=True)),
                ('return_notes', models.TextField(blank=True, help_text='Condition of the book at the time of return, damage notes, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, help_text='Staff member who issued the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.member')),
                ('owner', models.ForeignKey(help_text='Library admin who owns this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='member_transactions', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, help_text='Staff member who received the returned book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-issue_date'],
            },
        ),
    ]
