# Generated by Django 6.0.2 on 2026-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
